# Sveltia CMS Configuration
backend:
  name: github
  repo: ${SVELTIA_CMS_REPO}
  branch: ${SVELTIA_CMS_BRANCH}
  auth_scope: repo
  commit_messages:
    create: "Create {{collection}} "{{slug}}""
    update: "Update {{collection}} "{{slug}}""
    delete: "Delete {{collection}} "{{slug}}""
    uploadMedia: "[media] Upload "{{path}}""
    deleteMedia: "[media] Delete "{{path}}""

# Enable editorial workflow (draft, review, ready, published)
local_backend: true
publish_mode: editorial_workflow

# Media settings
media_folder: "public/images"
public_folder: "/images"
media_library:
  name: imagekit
  config:
    publicKey: ${IMAGEKIT_PUBLIC_KEY}
    privateKey: ${IMAGEKIT_PRIVATE_KEY}
    urlEndpoint: ${IMAGEKIT_URL}
    uploadFolder: "cms-uploads"

# Content Collections
collections:
  # Articles Collection
  - name: "articles"
    label: "Articles"
    folder: "content/articles"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Description", name: "description", widget: "text", required: true }
      - { label: "Publish Date", name: "publishDate", widget: "datetime", required: true }
      - { label: "Updated Date", name: "updatedDate", widget: "datetime", required: false }
      - { label: "Author", name: "author", widget: "relation", collection: "authors", value_field: "{{slug}}", search_fields: ["name"], display_fields: ["name"], required: true }
      - { label: "Category", name: "category", widget: "relation", collection: "categories", value_field: "{{slug}}", search_fields: ["name"], display_fields: ["name"], required: true }
      - { label: "Featured", name: "featured", widget: "boolean", default: false, required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: true, required: false }
      - label: "Featured Image"
        name: "image"
        widget: "object"
        required: true
        fields:
          - { label: "Image", name: "src", widget: "image", required: true }
          - { label: "Alt Text", name: "alt", widget: "string", required: true }
          - { label: "Caption", name: "caption", widget: "string", required: false }
          - { label: "Credit", name: "credit", widget: "string", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Reading Time (minutes)", name: "readingTime", widget: "number", required: false, value_type: "int" }
      - { label: "Free Access", name: "isAccessibleForFree", widget: "boolean", default: true, required: false }
      - { label: "Word Count", name: "wordCount", widget: "number", required: false, value_type: "int" }
      - { label: "Related Articles", name: "relatedArticles", widget: "relation", collection: "articles", search_fields: ["title"], value_field: "{{slug}}", display_fields: ["title"], multiple: true, required: false }
      - { label: "Content", name: "body", widget: "markdown", required: true }

  # Authors Collection
  - name: "authors"
    label: "Authors"
    folder: "content/authors"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    editor:
      preview: true
    fields:
      - { label: "Name", name: "name", widget: "string", required: true }
      - { label: "Title", name: "title", widget: "string", required: false }
      - { label: "Bio", name: "bio", widget: "text", required: true }
      - label: "Avatar"
        name: "avatar"
        widget: "object"
        required: true
        fields:
          - { label: "Image", name: "src", widget: "image", required: true }
          - { label: "Alt Text", name: "alt", widget: "string", default: "Author avatar", required: false }
      - label: "Social Media"
        name: "social"
        widget: "object"
        required: false
        fields:
          - { label: "Twitter", name: "twitter", widget: "string", required: false }
          - { label: "Facebook", name: "facebook", widget: "string", required: false }
          - { label: "Instagram", name: "instagram", widget: "string", required: false }
          - { label: "LinkedIn", name: "linkedin", widget: "string", required: false }
          - { label: "GitHub", name: "github", widget: "string", required: false }
          - { label: "Website", name: "website", widget: "string", required: false }
      - { label: "Featured", name: "featured", widget: "boolean", default: false, required: false }
      - { label: "Content", name: "body", widget: "markdown", required: false }

  # Categories Collection
  - name: "categories"
    label: "Categories"
    folder: "content/categories"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    editor:
      preview: true
    fields:
      - { label: "Name", name: "name", widget: "string", required: true }
      - { label: "Description", name: "description", widget: "text", required: true }
      - { label: "Color", name: "color", widget: "color", default: "#3b82f6", required: true }
      - label: "Image"
        name: "image"
        widget: "object"
        required: false
        fields:
          - { label: "Image", name: "src", widget: "image", required: true }
          - { label: "Alt Text", name: "alt", widget: "string", default: "Category image", required: false }
      - { label: "Featured", name: "featured", widget: "boolean", default: false, required: false }
      - { label: "Order", name: "order", widget: "number", default: 999, value_type: "int", required: false }
      - { label: "Content", name: "body", widget: "markdown", required: false }

  # Pages Collection
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Description", name: "description", widget: "text", required: true }
      - { label: "Publish Date", name: "publishDate", widget: "datetime", required: true }
      - { label: "Updated Date", name: "updatedDate", widget: "datetime", required: false }
      - label: "Featured Image"
        name: "image"
        widget: "object"
        required: false
        fields:
          - { label: "Image", name: "src", widget: "image", required: true }
          - { label: "Alt Text", name: "alt", widget: "string", required: true }
      - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false }
      - { label: "Layout", name: "layout", widget: "select", options: ["default", "wide", "full"], default: "default", required: true }
      - { label: "Show Table of Contents", name: "showToc", widget: "boolean", default: false, required: false }
      - { label: "Show Comments", name: "showComments", widget: "boolean", default: false, required: false }
      - { label: "No Index", name: "noindex", widget: "boolean", default: false, required: false }
      - { label: "Content", name: "body", widget: "markdown", required: true }